### ISSUE TITLE
XPathExpression issue with the registry

### ISSUE THREAD

**Issue by JoepDemey** [erasmus-without-paper/ewp-specs-api-registry#11]
Hi, I use XPathExpressions to get information (hei information, urls,...) from the registry. The expression "//r:host/r:apis-implemented" used to get me all the hosts, but I just noticed it isn't working anymore, I don't know for how long. What I do know, is in my code, I was expecting the namespace xmlns:r="https://github.com/erasmus-without-paper/ewp-specs-api-registry/tree/stable-v1", but now there is a xmlns:r1="https://github.com/erasmus-without-paper/ewp-specs-api-registry/blob/stable-v1/manifest-entry.xsd"

I use the following xml example to test my XPathExpression online (http://xpather.com/), but can't get it to work.

When I change the default namespace to xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-registry/blob/stable-v1/manifest-entry.xsd", the XPathExpression "//r1:host/r1:apis-implemented" works just fine. Is it possible that this should be the default namespace? Or can anyone point me in the right direction for the XPathExpression I need with the current namespaces?

<catalogue
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-registry/tree/stable-v1"
    xmlns:d6="https://github.com/erasmus-without-paper/ewp-specs-api-discovery/blob/stable-v6/manifest-entry.xsd"
    xmlns:e2="https://github.com/erasmus-without-paper/ewp-specs-api-echo/blob/stable-v2/manifest-entry.xsd"
    xmlns:ewp="https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/stable-v1/common-types.xsd"
    xmlns:ia2="https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v2/manifest-entry.xsd"
    xmlns:iac2="https://github.com/erasmus-without-paper/ewp-specs-api-iia-cnr/blob/stable-v2/manifest-entry.xsd"
    xmlns:in2="https://github.com/erasmus-without-paper/ewp-specs-api-institutions/blob/stable-v2/manifest-entry.xsd"
    xmlns:ou2="https://github.com/erasmus-without-paper/ewp-specs-api-ounits/blob/stable-v2/manifest-entry.xsd"
    xmlns:r1="https://github.com/erasmus-without-paper/ewp-specs-api-registry/blob/stable-v1/manifest-entry.xsd"
    xmlns:sec="https://github.com/erasmus-without-paper/ewp-specs-sec-intro/tree/stable-v2"
    xmlns:sec-A0="https://github.com/erasmus-without-paper/ewp-specs-sec-cliauth-none/tree/stable-v1"
    xmlns:sec-A1="https://github.com/erasmus-without-paper/ewp-specs-sec-cliauth-tlscert/tree/stable-v1"
    xmlns:sec-A2="https://github.com/erasmus-without-paper/ewp-specs-sec-cliauth-httpsig/tree/stable-v1"
    xmlns:sec-B1="https://github.com/erasmus-without-paper/ewp-specs-sec-srvauth-tlscert/tree/stable-v1"
    xmlns:sec-B2="https://github.com/erasmus-without-paper/ewp-specs-sec-srvauth-httpsig/tree/stable-v1"
    xmlns:sec-C1="https://github.com/erasmus-without-paper/ewp-specs-sec-reqencr-tls/tree/stable-v1"
    xmlns:sec-D1="https://github.com/erasmus-without-paper/ewp-specs-sec-resencr-tls/tree/stable-v1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/stable-v1/common-types.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-architecture/stable-v1/common-types.xsd

        https://github.com/erasmus-without-paper/ewp-specs-api-registry/tree/stable-v1
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-registry/stable-v1/catalogue.xsd

        https://github.com/erasmus-without-paper/ewp-specs-api-discovery/blob/stable-v6/manifest-entry.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-discovery/stable-v6/manifest-entry.xsd

        https://github.com/erasmus-without-paper/ewp-specs-api-echo/blob/stable-v2/manifest-entry.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-echo/stable-v2/manifest-entry.xsd

        https://github.com/erasmus-without-paper/ewp-specs-api-registry/blob/stable-v1/manifest-entry.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-registry/stable-v1/manifest-entry.xsd

        https://github.com/erasmus-without-paper/ewp-specs-api-institutions/blob/stable-v2/manifest-entry.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-institutions/stable-v2/manifest-entry.xsd

        https://github.com/erasmus-without-paper/ewp-specs-api-ounits/blob/stable-v2/manifest-entry.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-ounits/stable-v2/manifest-entry.xsd

        https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v2/manifest-entry.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-iias/stable-v2/manifest-entry.xsd

        https://github.com/erasmus-without-paper/ewp-specs-api-iia-cnr/blob/stable-v2/manifest-entry.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-iia-cnr/stable-v2/manifest-entry.xsd

        https://github.com/erasmus-without-paper/ewp-specs-sec-intro/tree/stable-v2
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-sec-intro/stable-v2/schema.xsd

        https://github.com/erasmus-without-paper/ewp-specs-sec-cliauth-none/tree/stable-v1
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-sec-cliauth-none/stable-v1/security-entries.xsd

        https://github.com/erasmus-without-paper/ewp-specs-sec-cliauth-tlscert/tree/stable-v1
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-sec-cliauth-tlscert/stable-v1/security-entries.xsd

        https://github.com/erasmus-without-paper/ewp-specs-sec-cliauth-httpsig/tree/stable-v1
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-sec-cliauth-httpsig/stable-v1/security-entries.xsd

        https://github.com/erasmus-without-paper/ewp-specs-sec-srvauth-tlscert/tree/stable-v1
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-sec-srvauth-tlscert/stable-v1/security-entries.xsd

        https://github.com/erasmus-without-paper/ewp-specs-sec-srvauth-httpsig/tree/stable-v1
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-sec-srvauth-httpsig/stable-v1/security-entries.xsd

        https://github.com/erasmus-without-paper/ewp-specs-sec-reqencr-tls/tree/stable-v1
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-sec-reqencr-tls/stable-v1/security-entries.xsd

        https://github.com/erasmus-without-paper/ewp-specs-sec-resencr-tls/tree/stable-v1
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-sec-resencr-tls/stable-v1/security-entries.xsd
    "
>
    <host>
        <ewp:admin-email>ewp-tech@lists.erasmuswithoutpaper.eu</ewp:admin-email>
        <ewp:admin-provider>EWP</ewp:admin-provider>
        <ewp:admin-notes>This host handles the EWP Registry Service.</ewp:admin-notes>
        <apis-implemented>
            <discovery
                xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-discovery/tree/stable-v6/manifest-entry.xsd"
                version="6.0.0"
            >
                <url>https://registry.erasmuswithoutpaper.eu/manifest-registry.xml</url>
            </discovery>
            <r1:registry version="1.3.0">
                <r1:catalogue-url>https://registry.erasmuswithoutpaper.eu/catalogue-v1.xml</r1:catalogue-url>
            </r1:registry>
        </apis-implemented>
    </host>
    <host>
        <ewp:admin-email>usos@agh.edu.pl</ewp:admin-email>
        <ewp:admin-provider>MUCI (USOS)</ewp:admin-provider>
        <apis-implemented>
            <d6:discovery version="6.0.0">
                <d6:url>https://ewp.usos.agh.edu.pl/manifest</d6:url>
            </d6:discovery>
            <e2:echo version="2.0.1">
                <e2:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </e2:http-security>
                <e2:url>https://ewp.usos.agh.edu.pl/echo</e2:url>
            </e2:echo>
            <in2:institutions version="2.2.0">
                <in2:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </in2:http-security>
                <in2:url>https://ewp.usos.agh.edu.pl/institutions</in2:url>
                <in2:max-hei-ids>1</in2:max-hei-ids>
            </in2:institutions>
            <ou2:organizational-units version="2.1.1">
                <ou2:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </ou2:http-security>
                <ou2:url>https://ewp.usos.agh.edu.pl/ounits</ou2:url>
                <ou2:max-ounit-ids>100</ou2:max-ounit-ids>
                <ou2:max-ounit-codes>100</ou2:max-ounit-codes>
            </ou2:organizational-units>
            <co1:courses
                xmlns:co1="https://github.com/erasmus-without-paper/ewp-specs-api-courses/blob/stable-v1/manifest-entry.xsd"
                version="0.7.1"
            >
                <co1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </co1:http-security>
                <co1:url>https://ewp.usos.agh.edu.pl/courses</co1:url>
                <co1:max-los-ids>100</co1:max-los-ids>
                <co1:max-los-codes>100</co1:max-los-codes>
            </co1:courses>
            <ia6:iias
                xmlns:ia6="https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v6/manifest-entry.xsd"
                version="6.2.0"
            >
                <ia6:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </ia6:http-security>
                <ia6:get-url>https://ewp.usos.agh.edu.pl/iia/get</ia6:get-url>
                <ia6:max-iia-ids>100</ia6:max-iia-ids>
                <ia6:max-iia-codes>100</ia6:max-iia-codes>
                <ia6:index-url>https://ewp.usos.agh.edu.pl/iia/index</ia6:index-url>
                <ia6:stats-url>https://ewp.usos.agh.edu.pl/iia/stats</ia6:stats-url>
            </ia6:iias>
            <iac2:iia-cnr version="2.0.3">
                <iac2:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </iac2:http-security>
                <iac2:url>https://ewp.usos.agh.edu.pl/iia/cnr</iac2:url>
            </iac2:iia-cnr>
            <iaa1:iias-approval
                xmlns:iaa1="https://github.com/erasmus-without-paper/ewp-specs-api-iias-approval/blob/stable-v1/manifest-entry.xsd"
                version="1.0.0"
            >
                <iaa1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </iaa1:http-security>
                <iaa1:url>https://ewp.usos.agh.edu.pl/iia/approval</iaa1:url>
                <iaa1:max-iia-ids>100</iaa1:max-iia-ids>
            </iaa1:iias-approval>
            <iaac1:iia-approval-cnr
                xmlns:iaac1="https://github.com/erasmus-without-paper/ewp-specs-api-iia-approval-cnr/blob/stable-v1/manifest-entry.xsd"
                version="1.0.0"
            >
                <iaac1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </iaac1:http-security>
                <iaac1:url>https://ewp.usos.agh.edu.pl/iia/approval/cnr</iaac1:url>
            </iaac1:iia-approval-cnr>
            <f1:factsheet
                xmlns:f1="https://github.com/erasmus-without-paper/ewp-specs-api-factsheet/blob/stable-v1/manifest-entry.xsd"
                version="1.1.0"
            >
                <f1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </f1:http-security>
                <f1:url>https://ewp.usos.agh.edu.pl/factsheet</f1:url>
                <f1:max-hei-ids>1</f1:max-hei-ids>
            </f1:factsheet>
            <im1:imobilities
                xmlns:im1="https://github.com/erasmus-without-paper/ewp-specs-api-imobilities/blob/stable-v1/manifest-entry.xsd"
                version="1.0.0"
            >
                <im1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </im1:http-security>
                <im1:get-url>https://ewp.usos.agh.edu.pl/imobilities/get</im1:get-url>
                <im1:max-omobility-ids>100</im1:max-omobility-ids>
                <im1:sends-notifications/>
            </im1:imobilities>
            <imc1:imobility-cnr
                xmlns:imc1="https://github.com/erasmus-without-paper/ewp-specs-api-imobility-cnr/blob/stable-v1/manifest-entry.xsd"
                version="1.0.0"
            >
                <imc1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </imc1:http-security>
                <imc1:url>https://ewp.usos.agh.edu.pl/imobilities/cnr</imc1:url>
                <imc1:max-omobility-ids>100</imc1:max-omobility-ids>
            </imc1:imobility-cnr>
            <om2:omobilities
                xmlns:om2="https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/blob/stable-v2/manifest-entry.xsd"
                version="2.0.0"
            >
                <om2:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </om2:http-security>
                <om2:get-url>https://ewp.usos.agh.edu.pl/omobilities/get</om2:get-url>
                <om2:index-url>https://ewp.usos.agh.edu.pl/omobilities/index</om2:index-url>
                <om2:max-omobility-ids>100</om2:max-omobility-ids>
                <om2:sends-notifications/>
            </om2:omobilities>
            <omc1:omobility-cnr
                xmlns:omc1="https://github.com/erasmus-without-paper/ewp-specs-api-omobility-cnr/blob/stable-v1/manifest-entry.xsd"
                version="1.0.0"
            >
                <omc1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </omc1:http-security>
                <omc1:url>https://ewp.usos.agh.edu.pl/omobilities/cnr</omc1:url>
                <omc1:max-omobility-ids>100</omc1:max-omobility-ids>
            </omc1:omobility-cnr>
            <oml1:omobility-las
                xmlns:oml1="https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/stable-v1/manifest-entry.xsd"
                version="1.2.0"
            >
                <oml1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </oml1:http-security>
                <oml1:get-url>https://ewp.usos.agh.edu.pl/la/get</oml1:get-url>
                <oml1:index-url>https://ewp.usos.agh.edu.pl/la/index</oml1:index-url>
                <oml1:update-url>https://ewp.usos.agh.edu.pl/la/update</oml1:update-url>
                <oml1:stats-url>https://ewp.usos.agh.edu.pl/la/stats</oml1:stats-url>
                <oml1:max-omobility-ids>100</oml1:max-omobility-ids>
            </oml1:omobility-las>
            <imt1:imobility-tors
                xmlns:imt1="https://github.com/erasmus-without-paper/ewp-specs-api-imobility-tors/blob/stable-v1/manifest-entry.xsd"
                version="1.0.0"
            >
                <imt1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </imt1:http-security>
                <imt1:get-url>https://ewp.usos.agh.edu.pl/tors/get</imt1:get-url>
                <imt1:index-url>https://ewp.usos.agh.edu.pl/tors/index</imt1:index-url>
                <imt1:max-omobility-ids>10</imt1:max-omobility-ids>
                <imt1:sends-notifications/>
            </imt1:imobility-tors>
            <imtc1:imobility-tor-cnr
                xmlns:imtc1="https://github.com/erasmus-without-paper/ewp-specs-api-imobility-tor-cnr/blob/stable-v1/manifest-entry.xsd"
                version="1.0.0"
            >
                <imtc1:http-security>
                    <sec:client-auth-methods>
                        <sec-A2:httpsig/>
                    </sec:client-auth-methods>
                    <sec:server-auth-methods>
                        <sec-B1:tlscert/>
                        <sec-B2:httpsig/>
                    </sec:server-auth-methods>
                </imtc1:http-security>
                <imtc1:url>https://ewp.usos.agh.edu.pl/tors/cnr</imtc1:url>
                <imtc1:max-omobility-ids>10</imtc1:max-omobility-ids>
            </imtc1:imobility-tor-cnr>
        </apis-implemented>
        <institutions-covered>
            <hei-id>agh.edu.pl</hei-id>
        </institutions-covered>
        <client-credentials-in-use>
            <rsa-public-key sha-256="d38c66f7b20156021c0b19464cba17bf70fb9fcb33752f20f6a6bd35a0a66a6f"/>
        </client-credentials-in-use>
        <server-credentials-in-use>
            <rsa-public-key sha-256="d38c66f7b20156021c0b19464cba17bf70fb9fcb33752f20f6a6bd35a0a66a6f"/>
        </server-credentials-in-use>
    </host>
</catalogue>

**Comment by mkurzydlowski** [comment]
"https://github.com/erasmus-without-paper/ewp-specs-api-registry/blob/stable-v1/manifest-entry.xsd" is the proper namespace:
https://github.com/erasmus-without-paper/ewp-specs-api-registry/blob/stable-v1/manifest-entry.xsd#L8-L9

So every thing seems fine. I don't recall changing it and neither has the catalogue file changed in this regard lately.

**Comment by JoepDemey** [comment]
It's ok, I got it to work
