### ISSUE TITLE
No institutions-covered and rsa-public-key

### ISSUE THREAD

**Issue by demilatof** [erasmus-without-paper/ewp-specs-api-registry#12]
In the catalogue.xsd, the annotation for the element rsa-public-key states 

> The client who is in possession of the private part of this key **is allowed to
> make requests in the name of the institutions listed in the adjacent
> `institutions-covered` element**.

But I see a host needed for the API Validator that has no "institutions-covered" element.
How should I do? I think I have to ignore the request, as if that element were not in the catalogue, but if so I don't understand the reason to have  minOccurs="0" for institutions-covered element

**Comment by mkurzydlowski** [comment]
Clients in the EWP network may cover no HEI. Such requests originate from the EWP network but they must not be granted any data that is restricted to a specific HEI (they are treated as anonymous requests) and that is why this case is added to the API validator.

**Comment by demilatof** [comment]
> Clients in the EWP network may cover no HEI. 

Yes, I see, even if I don't understand why; I think it would be much better using a dummy Hei, if needed.

> Such requests originate from the EWP network but they must not be granted any data that is restricted to a specific HEI (they are treated as anonymous requests) and that is why this case is added to the API validator.

But if I want to grant an anonymous access to my API I declare: 

```
<sec:client-auth-methods>
<sec-A0:anonymous/>
</sec:client-auth-methods>
```

But, for example, the anonymous method is forbidden for Echo API.
The question is: may I decide to serve only request that can I associate to a recognized HEI, or I'm compelled to serve the response to any request that has an RSA PK?
My HEI is the owner of data, I think that it has the right to accept or not data to clients that cannot be identified.
My HEI is the owner of the data, I think that it has the right to accept or not to serve data to clients that cannot be identified.

**Comment by mkurzydlowski** [comment]
> The question is: may I decide to serve only request that can I associate to a recognized HEI, or I'm compelled to serve the response to any request that has an RSA PK?

You must not may for data that is private. Signing a request with client credentials only makes a request "less anonymous", as we know it originates from an EWP node.

> My HEI is the owner of the data, I think that it has the right to accept or not to serve data to clients that cannot be identified.

Exactly, you mustn't serve private data to clients that are not authorized to access them.

**Comment by demilatof** [comment]
Ok, thanks

> > The question is: may I decide to serve only request that can I associate to a recognized HEI, or I'm compelled to serve the response to any request that has an RSA PK?
> 
> You must not may for data that is private. Signing a request with client credentials only makes a request "less anonymous", as we know it originates from an EWP node.
> 
> > My HEI is the owner of the data, I think that it has the right to accept or not to serve data to clients that cannot be identified.
> 
> Exactly, you mustn't serve private data to clients that are not authorized to access them.
