### ISSUE TITLE
If-Modified-Since ignored by Registry service

### ISSUE THREAD

**Issue by maurovanetti** [erasmus-without-paper/ewp-specs-api-registry#13]
The [Caching](https://github.com/erasmus-without-paper/ewp-specs-api-registry?tab=readme-ov-file#caching) section reads:

> When querying the Registry, clients MAY also utilize web caching techniques, such as [If-Modified-Since](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.25) or [If-None-Match](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.26) HTTP headers. If these request headers are used properly, the Registry will respond with HTTP 304 Not Modified status (thus reducing the time you need for receiving and loading the catalogue).

And yet, if I call https://registry.erasmuswithoutpaper.eu/catalogue-v1.xml with

`If-Modified-Since: Wed, 12 Jun 2024 09:30:00 GMT`

set to any recent time, the response is always HTTP 200 OK.

**Comment by janinamincer-daszkiewicz** [comment]
Thank you Mauro for reporting. We are working on the patch, will notify you when we install the changes and will ask for testing.

**Comment by maurovanetti** [comment]
Cool!

**Comment by mkurzydlowski** [comment]
@maurovanetti, you can now test if it works in the DEV registry.

**Comment by maurovanetti** [comment]
It works perfectly! Thank you.

**Comment by mkurzydlowski** [comment]
PROD registry should also work now.
