### ISSUE TITLE
How to contact service provider of an API

### ISSUE THREAD

**Issue by umesh-qs** [erasmus-without-paper/ewp-specs-api-registry#7]
Hi,
Please suggest how one service provider can contact another service provider for reporting any issues if there is no mention of any contact in their manifest. Also even if the contact is there it does not work. For example USOS-DAK@adm.uw.edu.pl.

PS: In an email to the registry service maintainers at "usos@usos.edu.pl", we got a blunt reply that they are not responsible for it.

**Comment by janinamincer-daszkiewicz** [comment]
This is exactly the situation. The registry administrator is responsible only for adding the new URLs to the registry. The registry administrator is not the contact point for all HEIs in Europe.

**Comment by janinamincer-daszkiewicz** [comment]
We are also not responsible for the errors in this manifest file: https://qsucimsapi.moveonfr.com/ewpapi/manifest. Content of the manifest file is fully under control of the local maintainers.

**Comment by umesh-qs** [comment]
Yes but you are for sure in control of whitelisting the core internet domain, which sometimes takes a week. So some of the errors will remain until you whitelist them.

**Comment by janinamincer-daszkiewicz** [comment]
On general it does not take more than 1-2 days and you can definitely take that time into account. The new SCHACs can be first added to the registry and then to the manifest file.

**Comment by umesh-qs** [comment]
Another approach can be automatically whitelisting the core internet domain based on the manifest instead of the manual emails process. But for now, let's not discuss this here. Maybe a separate issue can be opened.
 
This issue is getting lost. How to contact the respective service provider for any API issues? You are also a manifest host. It will be good to hear your perspective on it.

**Comment by janinamincer-daszkiewicz** [comment]
> Another approach can be automatically whitelisting the core internet domain based on the manifest instead of the manual emails process.

That would mean no control at all and would not be compliant with the official entry procedure to the network. Anyway I hope that this issue will be solved with the new Registration Portal where authorised representatives of the HEIs will be in full control of their APIs and their manifest files. This is work in progress.
This should also solve the issue with many duplicates in the network, currently created by service providers who suport many institutions.

> How to contact the respective service provider for any API issues? You are also a manifest host. It will be good to hear your perspective on it.

I am not the manifest host. I represent MUCI and deliver software to HEIs in Poland. These HEIs install this software at their premises and take care of it. I do not run EWP connector for the University of Warsaw as you probably assume and suggest.

**Comment by umesh-qs** [comment]
Not sure how the official procedure is any different than having an automatic whitelist/removing from the whitelist in terms of control. if it is for log then I guess manifest backup is being taken to serve as proof of adding/removing hei id.

Apologies for assuming that you are the owner of "University of Warsaw" manifest. Still, your inputs can help.

**Comment by janinamincer-daszkiewicz** [comment]
> Not sure how the official procedure is any different than having an automatic whitelist/removing from the whitelist in terms of control. if it is for log then I guess manifest backup is being taken to serve as proof of adding/removing hei id.

The new software providers have to sign the MoU with EUF and prove that they represent clients they pretend to. The old partners from the EWP project are treated in a special way. So better not complain :) 

> Still, your inputs can help.

How? If HEIs change WWW domains, e-mail addresses, and even names this is fully *their* responsibility to keep the important imformation, in particular contact details, up to date. 
You might for example write an e-mail to the main contact address of the University of Warsaw.
In that particular case I could help and already forwared your e-mail to a person I know. If that would be some institution in France, I would not be able to help.

**Comment by umesh-qs** [comment]
Can we make admin-email mandatory in the manifest? It may not help in case of the wrong email but that should be a rare case.

**Comment by janinamincer-daszkiewicz** [comment]
Yes, why not, let's wait for the opinion of the others.

**Comment by georgschermann** [comment]
We as a service provider removed the admin email addresses from the manifests because we received **a lot** of unrelated e-mails from all sorts of stakeholders which didn't have anything to do with technical issues. I am not sure if we would put a meaningful e-mail address there under any conditions. One thing wich may be possible would be a different e-mail addresses like general contact vs. technical/api contact or something like this. For us usual procedure is to contact the University to contact their provider / IT.

**Comment by janinamincer-daszkiewicz** [comment]
During the Infrastructure forum we suggested to follow some good practices in the EWP network, like using institutional emails and adding information about the providers. Let's hope this will help to have access to contact info.

**Comment by umesh-qs** [comment]
@janinamincer-daszkiewicz 
would it be possible to share the good practices discussed and how this issue will be addressed

**Comment by janinamincer-daszkiewicz** [comment]
OK, I will copy from the presentation shared with mobility software providers at the Infrastructure Forum:

1. Don’t use private emails in the manifest files (GDPR!).  
Use [ewp@uw.edu.pl](mailto:ewp@uw.edu.pl) instead of [janina.kowalska@uw.edu.pl](mailto:janina.kowalska@uw.edu.pl) 
https://github.com/erasmus-without-paper/ewp-specs-api-discovery/commit/035fbddca65d3ea4e6e4eb6148746d8aa109eaca 

2. Add Erasmus code. Remember about correct format: three chars for the country prefix, e.g. A__WIEN15 , PL_WARSAW01, IRLDUBLIN01

3. Spell correctly name of HEI, use proper language attribute, don’t  write it in capital letters:
<ns2:name xml:lang="pl">Uniwersytet Warszawski</ns2:name>
<ns2:name xml:lang="en">University of Warsaw</ns2:name>

4.  Add information about provider to the first line of admin-notes:
<ewp:admin-notes>Provider: MUCI (USOS)</ewp:admin-notes>
<ewp:admin-notes>Provider: Gent University (OASIS)</ewp:admin-notes>
<ewp:admin-notes>Provider: Masaryk University (ISOIS)</ewp:admin-notes>

**Comment by umesh-qs** [comment]
Not sure which presentation are you referring to. Haven't received any. But on the points mentioned, I don't see any mention of admin email being mandatory. Without that how is this issue getting resolved?

**Comment by janinamincer-daszkiewicz** [comment]
Presentation from the Infrastructure Forum. You was taking part, as I remember. Presentation is available at the web URL which was shared with the participants.

Good practices need not be mandatory and I do hope that all will start following them.  If you have a problem with contacting any provider - let me know.

**Comment by umesh-qs** [comment]
I am sorry I don't have any such document that points to the good practices mentioned in the this discussion. May be you can post the link here for everyone's reference.

Why can't email/group email be made mandatory in the manifest. Has there been an objection by lot of manifest owners?
Objective should be to remove manual process.

**Comment by umesh-qs** [comment]
Let me add to my previous comment. From our experience, people only use the admin email when there is genuine technical need. So far 95% people who contacted us had a genuine question/query.

**Comment by janinamincer-daszkiewicz** [comment]
I will send you the link by email.

I do not remember anybody suggesting to make email mandatory at the Infrastructure Forum. This is the place for discussing such issues and getting support for them

Anyway, in my opinion making it mandatory will not solve the problem if there is any.
If a provider intentionally breaks good practices in the network, the same provider will put fake email to the manifest file if the field is mandatory.

I prefer to base our decisions on some commonly agreed rules.

**Comment by umesh-qs** [comment]
I do not know what is this "Infrastructure Forum", and nor do I remember any discussion on this topic on any meetings I was part of.

I do not agree with your logic. If I go by that then I can do this at multiple places in the entire EWP network. And I can defend it by your logic after screwing up the network at multiple places. When you make it mandatory then it has to be a genuine email. 

You might have a preference that we are not inclined with. So I asked earlier, how many manifest provider has problem with making it mandatory. Have we asked this to everyone in the network?

**Comment by janinamincer-daszkiewicz** [comment]
QS Unisolutions have been invited for the meetings of the Infrastructure Forum, as one of the mobility software providers.

I see that we have different opinions. If you wish you can raise this issue at another meeting. This is the role of these meetings - to have a forum for sharing opinions.

As you see not many share their opinion on this issue here .

**Comment by umesh-qs** [comment]
It seems there was a confusion on agenda of these meetings. Hope we are not taking these meeting as default yes by the participants. There should be an explicit opportunity given to approve the API changes.

**Comment by janinamincer-daszkiewicz** [comment]
Of course not. These meeting are to discuss and make final decisions. Some decisions have already been made, some APIs have already been upgraded, some comments have been sent and are discussed in the other GitHub isses, e.g. https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/issues/44.

Which does not mean that it is good to all of us, software developers, to discuss them forever. For the time being the decision is - do not change the status of the admin email.

**Comment by umesh-qs** [comment]
We in MoveOn have no idea about the decision made. Can you share how, when and who made this decision to not change the status of admin email?

**Comment by janinamincer-daszkiewicz** [comment]
It has been a decision of tech partners in the project. We internally discussed various issues raised in GitHub and decided which ones to take into consideration. Then we presented the change proposals at the meetings. Nobody objected that this issue is missing.

**Comment by umesh-qs** [comment]
@janinamincer-daszkiewicz wrong to say nobody objected. And let me point out the rules of API changes. Can we know the list of partners who approved this.
![image](https://user-images.githubusercontent.com/53461949/159250793-045cc459-6d35-49ab-9c56-b0bc3393e981.png)

**Comment by sascoms** [comment]
We are in favor of this proposal. Yet two points to add:

1. They should be mandatory. We all know that it is not that difficult to add this information to the manifest files.

2. Provider name deserves its own field name, not in notes-field. (It has its own field in the LA APIs).

Similar ref. issue we opened on May 2021: https://github.com/erasmus-without-paper/general-issues/issues/35



> OK, I will copy from the presentation shared with mobility software providers at the Infrastructure Forum:
> 
> 1. Don’t use private emails in the manifest files (GDPR!).
>    Use [ewp@uw.edu.pl](mailto:ewp@uw.edu.pl) instead of [janina.kowalska@uw.edu.pl](mailto:janina.kowalska@uw.edu.pl)
>    [erasmus-without-paper/ewp-specs-api-discovery@035fbdd](https://github.com/erasmus-without-paper/ewp-specs-api-discovery/commit/035fbddca65d3ea4e6e4eb6148746d8aa109eaca)
> 2. Add Erasmus code. Remember about correct format: three chars for the country prefix, e.g. A__WIEN15 , PL_WARSAW01, IRLDUBLIN01
> 3. Spell correctly name of HEI, use proper language attribute, don’t  write it in capital letters:
>    <ns2:name xml:lang="pl">Uniwersytet Warszawski</ns2:name>
>    <ns2:name xml:lang="en">University of Warsaw</ns2:name>
> 4. Add information about provider to the first line of admin-notes:
>    ewp:admin-notesProvider: MUCI (USOS)</ewp:admin-notes>
>    ewp:admin-notesProvider: Gent University (OASIS)</ewp:admin-notes>
>    ewp:admin-notesProvider: Masaryk University (ISOIS)</ewp:admin-notes>

**Comment by sascoms** [comment]
@umesh-qs  We also mentioned this problem in our "EWP Technical Problems Report" we have published in recent months. 

A quote from that report:
**No common website or portal where providers can communicate with each other and open tickets related to the EWP data exchange problems in between.**

We, back in 2020, developed https://ewp.diaboard.com as an issue tracking system, where providers/partners can report issues to each other and also track EWP exchange issues. We currently track and log all our EWP-related issues we report to the other providers on this portal. 

If it would be of use, it is open to all and free.


> Hi, Please suggest how one service provider can contact another service provider for reporting any issues if there is no mention of any contact in their manifest. Also even if the contact is there it does not work. For example [USOS-DAK@adm.uw.edu.pl](mailto:USOS-DAK@adm.uw.edu.pl).
> 
> PS: In an email to the registry service maintainers at "[usos@usos.edu.pl](mailto:usos@usos.edu.pl)", we got a blunt reply that they are not responsible for it.

**Comment by janinamincer-daszkiewicz** [comment]
@sascoms Do I understand correctly:
- You want to have emails in the manifest files mandatory.
- They are not yet mandatory but they are not alway correct (you gave one example, I can give more as I myself often use these emails to contact the manifest file owners; resently also to send invitations to the tech meetings).
- You blame for that the registry administrator.
- Making them mandatory will solve the problem.
Correct?

**Comment by sascoms** [comment]
> @sascoms Do I understand correctly:
> 
> * You want to have emails in the manifest files mandatory.

Yes for emails and provider/system name. Yet, @georgschermann had a note about not all HEIs have Erasmus Code. If that is clarified, that can also be included or excluded in mandatory fields. (Are there non-erasmus HEIs in the EWP network?)

> * They are not yet mandatory but they are not alway correct (you gave one example, I can give more as I myself often use these emails to contact the manifest file owners; resently also to send invitations to the tech meetings).

The example was given by @umesh-qs but still this is not a reason not to make them mandatory.

> * You blame for that the registry administrator.

For what?

> * Making them mandatory will solve the problem.
>   Correct?

Why not? 
Even if the email in the manifest is problematic, we will know the provider name and can reach some people from that provider name.

**Comment by janinamincer-daszkiewicz** [comment]
> Even if the email in the manifest is problematic, we will know the provider name and can reach some people from that provider name.

I already do that and it seems to work. Changing a field to mandatory will *not* solve the problem permanently. Also Registration Portal may bring a change. 
But that's my personal opinion. I will ask at the meeting what the other think as not many take part in this discussion. 

> (Are there non-erasmus HEIs in the EWP network?)

Yes, have a look at the Coverage Matrix.

**Comment by sascoms** [comment]
As this issue and my ref. issue (https://github.com/erasmus-without-paper/general-issues/issues/35) were opened 2021/March-May, that was the main need at that time. Since then, everybody found the contact information of each other and a way to connect.

We would like to have more information on the registration portal and what it brings to the EWP in the upcoming meetings.

Also we will see how the new maillist will work.

**Comment by janinamincer-daszkiewicz** [comment]
> We would like to have more information on the registration portal and what it brings to the EWP in the upcoming meetings.

This is one of the point in the agenda.

> Also we will see how the new maillist will work.

The new mailing list is up and running. Just reply to the subscribe request :)
There are still may pending subscription requests.
