### ISSUE TITLE
Multiple SCHACs used by one university

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-registry#8]
In the current production catalogue (14 June 2021), there are several universities listed with multiple SCHACs:
- S JONKOPI01 => hj.se | ju.se
- F PARIS468 => sante.sorbonne-universite.fr | sorbonne-universite.fr
- A BADEN01 => PH-NOE.AC.AT | ph-noe.ac.at
- NL LEIDEN01 => leidenuniv.nl | universiteitleiden.nl
- F PAU01 => FPAU01 | univ-pau.fr

Why doesn't the importing procedure enforce that there be a one-to-one mapping between each Erasmus code and SCHAC?

Would it be possible to enforce that each institution has just one SCHAC? It would make life much easier for client implementers.

**Comment by janinamincer-daszkiewicz** [comment]
This is not the task of the registry. Registry should be as passive as possible, as it in not authorised to make decisions on its own who is accepted and with what data. There are already problems with duplicates in the network which are much more problematic - they do make the communication impossible. Erasmus codes are not necessary for the correct functioning of the network.
I hope at least some of these problems  will be easier to track when we implement the Registration portal where institutions will register their installations.
